# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-02-02 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicineDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku_id', models.IntegerField()),
                ('sku_name', models.CharField(max_length=2048)),
                ('price', models.FloatField()),
                ('manufacturer_name', models.CharField(max_length=2048)),
                ('salt_name', models.CharField(max_length=2048)),
                ('drug_form', models.CharField(max_length=2048)),
                ('pack_size', models.CharField(max_length=2048)),
                ('strength', models.CharField(max_length=1024)),
                ('product_banned_flag', models.BooleanField()),
                ('unit', models.CharField(max_length=255)),
                ('price_per_unit', models.FloatField()),
            ],
        ),
    ]
