# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-02-02 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_auto_20210202_1506'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='medicineDetails',
            new_name='medicineDetail',
        ),
    ]
