# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-02-02 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_auto_20210202_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicinedetail',
            options={'managed': False},
        ),
    ]
