# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-02-02 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_auto_20210202_2327'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medicinedetail',
            table='medicine_medicinedetail',
        ),
    ]
