# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-02-02 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_auto_20210203_0155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicinedetail',
            options={},
        ),
    ]
