# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-02-02 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_auto_20210203_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedetail',
            name='price_per_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicinedetail',
            name='product_banned_flag',
            field=models.NullBooleanField(),
        ),
        migrations.AlterModelTable(
            name='medicinedetail',
            table=None,
        ),
    ]
