# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-02-02 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0009_auto_20210203_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedetail',
            name='manufacturer_name',
            field=models.CharField(blank=True, db_index=True, max_length=2048, null=True),
        ),
    ]
